CPP       = clang++ -g -O0 -Wall -Wextra -std=c++1z
MKDEPS    = g++ -MM -std=c++1z
MODULES   = main chess_pieces utils
HDRSRC    = ${MODULES:=.h}
CPPSRC    = ${MODULES:=.cpp}
EXECBIN   = main
OBJECTS   = ${CPPSRC:.cpp=.o}

all : ${EXECBIN}

${EXECBIN} : ${OBJECTS}
	${CPP} -o${EXECBIN} ${OBJECTS}

%.o : %.cpp
	${CPP} -c $<
ci :
	-git add ${ALLSRC} 
	-git commit -m "Automatically generated by Makefile"
	-git push

clean :
	- rm ${OBJECTS}

spotless : clean
	- rm ${EXECBIN}
